from flask import Flask, render_template, request, jsonify

app = Flask(__name__)

# Mapeamento completo baseado no documento Alma Lavada
REACOES = {
    frozenset(["cloro", "sabao_po"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["cloro", "multiuso"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["cloro", "amaciante"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["cloro", "lustra_moveis"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["cloro", "sabao_liquido"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["cloro", "desengordurante"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["cloro", "limpa_vidro"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["cloro", "cera_piso"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["cloro", "inseticida_domestico"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["cloro", "soda_caustica"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["cloro", "detergente"]): {"status": "CUIDADO", "mensagem": "Pode utilizar, mas com cuidado."},
    frozenset(["cloro", "agua"]): {"status": "PODE", "mensagem": "Mistura segura. Pode utilizar."},
    frozenset(["cloro", "bicarbonato"]): {"status": "INIBE", "mensagem": "Esta mistura inibe a ação dos produtos."},
    frozenset(["cloro", "vinagre"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["cloro", "removedor"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["cloro", "agua_oxigenada"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["cloro", "alcool"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["cloro", "agua_sanitaria"]): {"status": "PODE", "mensagem": "Mistura segura. Pode utilizar."},
    frozenset(["cloro", "lysoform"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["cloro", "solupan"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["cloro", "desengraxante"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["cloro", "desinfetante"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["cloro", "amonia"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["cloro", "sabao_barra"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["cloro", "pasta_panela"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["cloro", "cloro_gel"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["sabao_po", "multiuso"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["sabao_po", "amaciante"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["sabao_po", "lustra_moveis"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["sabao_po", "sabao_liquido"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["sabao_po", "desengordurante"]): {"status": "PODE", "mensagem": "Mistura segura. Pode utilizar."},
    frozenset(["sabao_po", "limpa_vidro"]): {"status": "INIBE", "mensagem": "Esta mistura inibe a ação dos produtos."},
    frozenset(["sabao_po", "cera_piso"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["sabao_po", "inseticida_domestico"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["sabao_po", "soda_caustica"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["sabao_po", "detergente"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["sabao_po", "agua"]): {"status": "PODE", "mensagem": "Mistura segura. Pode utilizar."},
    frozenset(["sabao_po", "bicarbonato"]): {"status": "CUIDADO", "mensagem": "Pode utilizar, mas com cuidado."},
    frozenset(["sabao_po", "vinagre"]): {"status": "CUIDADO", "mensagem": "Pode utilizar, mas com cuidado."},
    frozenset(["sabao_po", "removedor"]): {"status": "INIBE", "mensagem": "Esta mistura inibe a ação dos produtos."},
    frozenset(["sabao_po", "agua_oxigenada"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["sabao_po", "alcool"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["sabao_po", "agua_sanitaria"]): {"status": "INIBE", "mensagem": "Esta mistura inibe a ação dos produtos."},
    frozenset(["sabao_po", "lysoform"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["sabao_po", "solupan"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["sabao_po", "desengraxante"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["sabao_po", "desinfetante"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["sabao_po", "amonia"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["sabao_po", "sabao_barra"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["sabao_po", "pasta_panela"]): {"status": "CUIDADO", "mensagem": "Pode utilizar, mas com cuidado."},
    frozenset(["sabao_po", "cloro_gel"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["multiuso", "amaciante"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["multiuso", "lustra_moveis"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["multiuso", "sabao_liquido"]): {"status": "CUIDADO", "mensagem": "Pode utilizar, mas com cuidado."},
    frozenset(["multiuso", "desengordurante"]): {"status": "CUIDADO", "mensagem": "Pode utilizar, mas com cuidado."},
    frozenset(["multiuso", "limpa_vidro"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["multiuso", "cera_piso"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["multiuso", "inseticida_domestico"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["multiuso", "soda_caustica"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["multiuso", "detergente"]): {"status": "INIBE", "mensagem": "Esta mistura inibe a ação dos produtos."},
    frozenset(["multiuso", "agua"]): {"status": "INIBE", "mensagem": "Esta mistura inibe a ação dos produtos."},
    frozenset(["multiuso", "bicarbonato"]): {"status": "INIBE", "mensagem": "Esta mistura inibe a ação dos produtos."},
    frozenset(["multiuso", "vinagre"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["multiuso", "removedor"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["multiuso", "agua_oxigenada"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["multiuso", "alcool"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["multiuso", "agua_sanitaria"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["multiuso", "lysoform"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["multiuso", "solupan"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["multiuso", "desengraxante"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["multiuso", "desinfetante"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["multiuso", "amonia"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["multiuso", "sabao_barra"]): {"status": "CUIDADO", "mensagem": "Pode utilizar, mas com cuidado."},
    frozenset(["multiuso", "pasta_panela"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["multiuso", "cloro_gel"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["amaciante", "lustra_moveis"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["amaciante", "sabao_liquido"]): {"status": "PODE", "mensagem": "Mistura segura. Pode utilizar."},
    frozenset(["amaciante", "desengordurante"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["amaciante", "limpa_vidro"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["amaciante", "cera_piso"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["amaciante", "inseticida_domestico"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["amaciante", "soda_caustica"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["amaciante", "detergente"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["amaciante", "agua"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["amaciante", "bicarbonato"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["amaciante", "vinagre"]): {"status": "INIBE", "mensagem": "Esta mistura inibe a ação dos produtos."},
    frozenset(["amaciante", "removedor"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["amaciante", "agua_oxigenada"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["amaciante", "alcool"]): {"status": "CUIDADO", "mensagem": "Pode utilizar, mas com cuidado."},
    frozenset(["amaciante", "agua_sanitaria"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["amaciante", "lysoform"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["amaciante", "solupan"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["amaciante", "desengraxante"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["amaciante", "desinfetante"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["amaciante", "amonia"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["amaciante", "sabao_barra"]): {"status": "INIBE", "mensagem": "Esta mistura inibe a ação dos produtos."},
    frozenset(["amaciante", "pasta_panela"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["amaciante", "cloro_gel"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["lustra_moveis", "sabao_liquido"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["lustra_moveis", "desengordurante"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["lustra_moveis", "limpa_vidro"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["lustra_moveis", "cera_piso"]): {"status": "PODE", "mensagem": "Mistura segura. Pode utilizar."},
    frozenset(["lustra_moveis", "inseticida_domestico"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["lustra_moveis", "soda_caustica"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["lustra_moveis", "detergente"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["lustra_moveis", "agua"]): {"status": "PODE", "mensagem": "Mistura segura. Pode utilizar."},
    frozenset(["lustra_moveis", "bicarbonato"]): {"status": "INIBE", "mensagem": "Esta mistura inibe a ação dos produtos."},
    frozenset(["lustra_moveis", "vinagre"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["lustra_moveis", "removedor"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["lustra_moveis", "agua_oxigenada"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["lustra_moveis", "alcool"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["lustra_moveis", "agua_sanitaria"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["lustra_moveis", "lysoform"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["lustra_moveis", "solupan"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["lustra_moveis", "desengraxante"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["lustra_moveis", "desinfetante"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["lustra_moveis", "amonia"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["lustra_moveis", "sabao_barra"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["lustra_moveis", "pasta_panela"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["lustra_moveis", "cloro_gel"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["sabao_liquido", "desengordurante"]): {"status": "CUIDADO", "mensagem": "Pode utilizar, mas com cuidado."},
    frozenset(["sabao_liquido", "limpa_vidro"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["sabao_liquido", "cera_piso"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["sabao_liquido", "inseticida_domestico"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["sabao_liquido", "soda_caustica"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["sabao_liquido", "detergente"]): {"status": "PODE", "mensagem": "Mistura segura. Pode utilizar."},
    frozenset(["sabao_liquido", "agua"]): {"status": "PODE", "mensagem": "Mistura segura. Pode utilizar."},
    frozenset(["sabao_liquido", "bicarbonato"]): {"status": "PODE", "mensagem": "Mistura segura. Pode utilizar."},
    frozenset(["sabao_liquido", "vinagre"]): {"status": "INIBE", "mensagem": "Esta mistura inibe a ação dos produtos."},
    frozenset(["sabao_liquido", "removedor"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["sabao_liquido", "agua_oxigenada"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["sabao_liquido", "alcool"]): {"status": "INIBE", "mensagem": "Esta mistura inibe a ação dos produtos."},
    frozenset(["sabao_liquido", "agua_sanitaria"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["sabao_liquido", "lysoform"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["sabao_liquido", "solupan"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["sabao_liquido", "desengraxante"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["sabao_liquido", "desinfetante"]): {"status": "CUIDADO", "mensagem": "Pode utilizar, mas com cuidado."},
    frozenset(["sabao_liquido", "amonia"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["sabao_liquido", "sabao_barra"]): {"status": "CUIDADO", "mensagem": "Pode utilizar, mas com cuidado."},
    frozenset(["sabao_liquido", "pasta_panela"]): {"status": "CUIDADO", "mensagem": "Pode utilizar, mas com cuidado."},
    frozenset(["sabao_liquido", "cloro_gel"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["desengordurante", "limpa_vidro"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["desengordurante", "cera_piso"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["desengordurante", "inseticida_domestico"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["desengordurante", "soda_caustica"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["desengordurante", "detergente"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["desengordurante", "agua"]): {"status": "PODE", "mensagem": "Mistura segura. Pode utilizar."},
    frozenset(["desengordurante", "bicarbonato"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["desengordurante", "vinagre"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["desengordurante", "removedor"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["desengordurante", "agua_oxigenada"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["desengordurante", "alcool"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["desengordurante", "agua_sanitaria"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["desengordurante", "lysoform"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["desengordurante", "solupan"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["desengordurante", "desengraxante"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["desengordurante", "desinfetante"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["desengordurante", "amonia"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["desengordurante", "sabao_barra"]): {"status": "CUIDADO", "mensagem": "Pode utilizar, mas com cuidado."},
    frozenset(["desengordurante", "pasta_panela"]): {"status": "CUIDADO", "mensagem": "Pode utilizar, mas com cuidado."},
    frozenset(["desengordurante", "cloro_gel"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["limpa_vidro", "cera_piso"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["limpa_vidro", "inseticida_domestico"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["limpa_vidro", "soda_caustica"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["limpa_vidro", "detergente"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["limpa_vidro", "agua"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["limpa_vidro", "bicarbonato"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["limpa_vidro", "vinagre"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["limpa_vidro", "removedor"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["limpa_vidro", "agua_oxigenada"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["limpa_vidro", "alcool"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["limpa_vidro", "agua_sanitaria"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["limpa_vidro", "lysoform"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["limpa_vidro", "solupan"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["limpa_vidro", "desengraxante"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["limpa_vidro", "desinfetante"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["limpa_vidro", "amonia"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["limpa_vidro", "sabao_barra"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["limpa_vidro", "pasta_panela"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["limpa_vidro", "cloro_gel"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["cera_piso", "inseticida_domestico"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["cera_piso", "soda_caustica"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["cera_piso", "detergente"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["cera_piso", "agua"]): {"status": "CUIDADO", "mensagem": "Pode utilizar, mas com cuidado."},
    frozenset(["cera_piso", "bicarbonato"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["cera_piso", "vinagre"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["cera_piso", "removedor"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["cera_piso", "agua_oxigenada"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["cera_piso", "alcool"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["cera_piso", "agua_sanitaria"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["cera_piso", "lysoform"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["cera_piso", "solupan"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["cera_piso", "desengraxante"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["cera_piso", "desinfetante"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["cera_piso", "amonia"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["cera_piso", "sabao_barra"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["cera_piso", "pasta_panela"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["cera_piso", "cloro_gel"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["inseticida_domestico", "soda_caustica"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["inseticida_domestico", "detergente"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["inseticida_domestico", "agua"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["inseticida_domestico", "bicarbonato"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["inseticida_domestico", "vinagre"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["inseticida_domestico", "removedor"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["inseticida_domestico", "agua_oxigenada"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["inseticida_domestico", "alcool"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["inseticida_domestico", "agua_sanitaria"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["inseticida_domestico", "lysoform"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["inseticida_domestico", "solupan"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["inseticida_domestico", "desengraxante"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["inseticida_domestico", "desinfetante"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["inseticida_domestico", "amonia"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["inseticida_domestico", "sabao_barra"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["inseticida_domestico", "pasta_panela"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["inseticida_domestico", "cloro_gel"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["soda_caustica", "detergente"]): {"status": "CUIDADO", "mensagem": "Pode utilizar, mas com cuidado."},
    frozenset(["soda_caustica", "agua"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["soda_caustica", "bicarbonato"]): {"status": "INIBE", "mensagem": "Esta mistura inibe a ação dos produtos."},
    frozenset(["soda_caustica", "vinagre"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["soda_caustica", "removedor"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["soda_caustica", "agua_oxigenada"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["soda_caustica", "alcool"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["soda_caustica", "agua_sanitaria"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["soda_caustica", "lysoform"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["soda_caustica", "solupan"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["soda_caustica", "desengraxante"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["soda_caustica", "desinfetante"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["soda_caustica", "amonia"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["soda_caustica", "sabao_barra"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["soda_caustica", "pasta_panela"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["soda_caustica", "cloro_gel"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["detergente", "agua"]): {"status": "PODE", "mensagem": "Mistura segura. Pode utilizar."},
    frozenset(["detergente", "bicarbonato"]): {"status": "INIBE", "mensagem": "Esta mistura inibe a ação dos produtos."},
    frozenset(["detergente", "vinagre"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["detergente", "removedor"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["detergente", "agua_oxigenada"]): {"status": "CUIDADO", "mensagem": "Pode utilizar, mas com cuidado."},
    frozenset(["detergente", "alcool"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["detergente", "agua_sanitaria"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["detergente", "lysoform"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["detergente", "solupan"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["detergente", "desengraxante"]): {"status": "CUIDADO", "mensagem": "Pode utilizar, mas com cuidado."},
    frozenset(["detergente", "desinfetante"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["detergente", "amonia"]): {"status": "CUIDADO", "mensagem": "Pode utilizar, mas com cuidado."},
    frozenset(["detergente", "sabao_barra"]): {"status": "CUIDADO", "mensagem": "Pode utilizar, mas com cuidado."},
    frozenset(["detergente", "pasta_panela"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["detergente", "cloro_gel"]): {"status": "CUIDADO", "mensagem": "Pode utilizar, mas com cuidado."},
    frozenset(["agua", "bicarbonato"]): {"status": "CUIDADO", "mensagem": "Pode utilizar, mas com cuidado."},
    frozenset(["agua", "vinagre"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["agua", "removedor"]): {"status": "PODE", "mensagem": "Mistura segura. Pode utilizar."},
    frozenset(["agua", "agua_oxigenada"]): {"status": "PODE", "mensagem": "Mistura segura. Pode utilizar."},
    frozenset(["agua", "alcool"]): {"status": "INIBE", "mensagem": "Esta mistura inibe a ação dos produtos."},
    frozenset(["agua", "agua_sanitaria"]): {"status": "PODE", "mensagem": "Mistura segura. Pode utilizar."},
    frozenset(["agua", "lysoform"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["agua", "solupan"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["agua", "desengraxante"]): {"status": "PODE", "mensagem": "Mistura segura. Pode utilizar."},
    frozenset(["agua", "desinfetante"]): {"status": "CUIDADO", "mensagem": "Pode utilizar, mas com cuidado."},
    frozenset(["agua", "amonia"]): {"status": "PODE", "mensagem": "Mistura segura. Pode utilizar."},
    frozenset(["agua", "sabao_barra"]): {"status": "PODE", "mensagem": "Mistura segura. Pode utilizar."},
    frozenset(["agua", "pasta_panela"]): {"status": "PODE", "mensagem": "Mistura segura. Pode utilizar."},
    frozenset(["agua", "cloro_gel"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["bicarbonato", "vinagre"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["bicarbonato", "removedor"]): {"status": "INIBE", "mensagem": "Esta mistura inibe a ação dos produtos."},
    frozenset(["bicarbonato", "agua_oxigenada"]): {"status": "INIBE", "mensagem": "Esta mistura inibe a ação dos produtos."},
    frozenset(["bicarbonato", "alcool"]): {"status": "INIBE", "mensagem": "Esta mistura inibe a ação dos produtos."},
    frozenset(["bicarbonato", "agua_sanitaria"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["bicarbonato", "lysoform"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["bicarbonato", "solupan"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["bicarbonato", "desengraxante"]): {"status": "INIBE", "mensagem": "Esta mistura inibe a ação dos produtos."},
    frozenset(["bicarbonato", "desinfetante"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["bicarbonato", "amonia"]): {"status": "INIBE", "mensagem": "Esta mistura inibe a ação dos produtos."},
    frozenset(["bicarbonato", "sabao_barra"]): {"status": "CUIDADO", "mensagem": "Pode utilizar, mas com cuidado."},
    frozenset(["bicarbonato", "pasta_panela"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["bicarbonato", "cloro_gel"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["vinagre", "removedor"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["vinagre", "agua_oxigenada"]): {"status": "CUIDADO", "mensagem": "Pode utilizar, mas com cuidado."},
    frozenset(["vinagre", "alcool"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["vinagre", "agua_sanitaria"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["vinagre", "lysoform"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["vinagre", "solupan"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["vinagre", "desengraxante"]): {"status": "INIBE", "mensagem": "Esta mistura inibe a ação dos produtos."},
    frozenset(["vinagre", "desinfetante"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["vinagre", "amonia"]): {"status": "INIBE", "mensagem": "Esta mistura inibe a ação dos produtos."},
    frozenset(["vinagre", "sabao_barra"]): {"status": "INIBE", "mensagem": "Esta mistura inibe a ação dos produtos."},
    frozenset(["vinagre", "pasta_panela"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["vinagre", "cloro_gel"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["removedor", "agua_oxigenada"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["removedor", "alcool"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["removedor", "agua_sanitaria"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["removedor", "lysoform"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["removedor", "solupan"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["removedor", "desengraxante"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["removedor", "desinfetante"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["removedor", "amonia"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["removedor", "sabao_barra"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["removedor", "pasta_panela"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["removedor", "cloro_gel"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["agua_oxigenada", "alcool"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["agua_oxigenada", "agua_sanitaria"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["agua_oxigenada", "lysoform"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["agua_oxigenada", "solupan"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["agua_oxigenada", "desengraxante"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["agua_oxigenada", "desinfetante"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["agua_oxigenada", "amonia"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["agua_oxigenada", "sabao_barra"]): {"status": "INIBE", "mensagem": "Esta mistura inibe a ação dos produtos."},
    frozenset(["agua_oxigenada", "pasta_panela"]): {"status": "CUIDADO", "mensagem": "Pode utilizar, mas com cuidado."},
    frozenset(["agua_oxigenada", "cloro_gel"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["alcool", "agua_sanitaria"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["alcool", "lysoform"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["alcool", "solupan"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["alcool", "desengraxante"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["alcool", "desinfetante"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["alcool", "amonia"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["alcool", "sabao_barra"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["alcool", "pasta_panela"]): {"status": "CUIDADO", "mensagem": "Pode utilizar, mas com cuidado."},
    frozenset(["alcool", "cloro_gel"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["agua_sanitaria", "lysoform"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["agua_sanitaria", "solupan"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["agua_sanitaria", "desengraxante"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["agua_sanitaria", "desinfetante"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["agua_sanitaria", "amonia"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["agua_sanitaria", "sabao_barra"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["agua_sanitaria", "pasta_panela"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["agua_sanitaria", "cloro_gel"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["lysoform", "solupan"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["lysoform", "desengraxante"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["lysoform", "desinfetante"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["lysoform", "amonia"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["lysoform", "sabao_barra"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["lysoform", "pasta_panela"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["lysoform", "cloro_gel"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["solupan", "desengraxante"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["solupan", "desinfetante"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["solupan", "amonia"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["solupan", "sabao_barra"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["solupan", "pasta_panela"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["solupan", "cloro_gel"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["desengraxante", "desinfetante"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["desengraxante", "amonia"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["desengraxante", "sabao_barra"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["desengraxante", "pasta_panela"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["desengraxante", "cloro_gel"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["desinfetante", "amonia"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["desinfetante", "sabao_barra"]): {"status": "CUIDADO", "mensagem": "Pode utilizar, mas com cuidado."},
    frozenset(["desinfetante", "pasta_panela"]): {"status": "INIBE", "mensagem": "Esta mistura inibe a ação dos produtos."},
    frozenset(["desinfetante", "cloro_gel"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["amonia", "sabao_barra"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["amonia", "pasta_panela"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["amonia", "cloro_gel"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["sabao_barra", "pasta_panela"]): {"status": "CUIDADO", "mensagem": "Pode utilizar, mas com cuidado."},
    frozenset(["sabao_barra", "cloro_gel"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
    frozenset(["pasta_panela", "cloro_gel"]): {"status": "NAO_PODE", "mensagem": "Não pode misturar."},
}


PRODUTOS_NOMES = {
    "cloro": "Cloro",
    "cloro_gel": "Cloro em Gel",
    "sabao_po": "Sabão em Pó",
    "multiuso": "Multiuso",
    "amaciante": "Amaciante",
    "lustra_moveis": "Lustra Móveis",
    "sabao_liquido": "Sabão Líquido",
    "desengordurante": "Desengordurante",
    "limpa_vidro": "Limpa Vidro",
    "cera_piso": "Cera de Piso",
    "inseticida": "Inseticida Doméstico",
    "soda_caustica": "Soda Cáustica",
    "detergente": "Detergente",
    "agua": "Água",
    "bicarbonato": "Bicarbonato de Sódio",
    "vinagre": "Vinagre",
    "removedor": "Removedor",
    "agua_oxigenada": "Água Oxigenada",
    "alcool": "Álcool",
    "agua_sanitaria": "Água Sanitária",
    "lysoform": "Lysoform",
    "solupan": "Solupan (Roxinho)",
    "desengraxante": "Desengraxante",
    "desinfetante": "Desinfetante",
    "amonia": "Amônia",
    "sabao_barra": "Sabão em Barra",
    "pasta_panela": "Pasta de Lavar Panela"
}

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/api/misturar', methods=['POST'])
def misturar():
    data = request.get_json()
    p1 = data.get('produto1')
    p2 = data.get('produto2')

    if not p1 or not p2:
        return jsonify({"erro": "Selecione dois produtos"}), 400

    par = frozenset([p1, p2])
    
    resultado = REACOES.get(par, {
        "status": "NAO_PODE",
        "mensagem": "Não pode misturar! Risco de reação química perigosa ou tóxica."
    })

    nome_p1 = PRODUTOS_NOMES.get(p1, p1)
    nome_p2 = PRODUTOS_NOMES.get(p2, p2)

    return jsonify({
        "produto1": nome_p1,
        "produto2": nome_p2,
        "status": resultado['status'],
        "mensagem": resultado['mensagem']
    })

if __name__ == '__main__':
    app.run(debug=True) 